# Simple example reference: https://github.com/prometheus/alertmanager/blob/master/doc/examples/simple.yml
global:
    smtp_smarthost: 'email-smtp.us-west-2.amazonaws.com:587'
    smtp_from: 'Alertmanager <alertmanager@example.com>'
    smtp_auth_username: 'FILLMEIN'
    smtp_auth_password: 'FILLMEIN'

templates:
- '/etc/alertmanager/template/*.tmpl'

route:
  receiver: 'team-X-mails'

receivers:
- name: 'team-X-mails'
  email_configs:
  - to: 'alertme@example.com'
