global:
 scrape_interval: 10s
 evaluation_interval: 10s

rule_files:
  - '/etc/prometheus/alert.rules'

scrape_configs:
 - job_name: 'prometheus'
   target_groups:
    - targets:
      - localhost:9090
 - job_name: 'blackboxhttp'
   metrics_path: /probe
   params:
     module: [http_2xx]
     target: [foo.example.com,bar.example.com,google.com]
   target_groups:
     - targets:
       - localhost:9115
 - job_name: 'node'
   target_groups:
     - targets:
        - localhost:9100
 - job_name: 'alertmanager'
   honor_labels: true
   target_groups:
    - targets:
       - localhost:9093
