rule_files:
  - '/etc/prometheus/alert.rules'

scrape_configs:
  - job_name: 'blackbox'
    scrape_interval: 5s
    scrape_timeout: 10s
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    target_groups:
      - targets:
        - prometheus.io
        - dabase.com
        - natalian.org
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*)(:80)?
        target_label: __param_target
        replacement: ${1}
      - source_labels: [__param_target]
        regex: (.*)
        target_label: instance
        replacement: ${1}
      - source_labels: []
        regex: .*
        target_label: __address__
        replacement: blackboxprober:9115  # Blackbox exporter.
